# 베이스 이미지 선택
FROM ubuntu:latest

# 패키지 업데이트 및 필요한 패키지 설치
RUN apt-get update \
    && apt-get install -y gcc make netcat \
    && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

# 호스트의 클라이언트 소스 코드를 컨테이너로 복사
COPY client.c .

# 클라이언트 소스 코드를 컴파일
RUN gcc -o client client.c

# 컨테이너가 시작될 때 실행할 명령어 설정 (실행 파일과 인자들을 넣으세요)
CMD ["./client"]

