@startuml
[*] --> Unlocked

Unlocked --> ReadLocked : Acquire Read Lock
ReadLocked --> Unlocked : Release Read Lock

Unlocked --> WriteLocked : Acquire Write Lock
WriteLocked --> Unlocked : Release Write Lock

state ReadLocked {
    [*] --> Reader
    Reader --> Reader : Acquire Read Lock
    Reader --> [*] : Release Read Lock
}

state WriteLocked {
    [*] --> Writer
    Writer --> [*] : Release Write Lock
}
@enduml
